### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by metrolan** [gristlabs/grist-omnibus#21]
I think grist-omnibus is a great idea.

I have created this directory structure:
/docker/gristo/persist.

Then in /docker/gristo I typed:
docker run \\
  -p 9999:80 \\
  -e URL=http://localhost:9999 \\
  -e TEAM=cool-beans \\
  -e EMAIL=owner@example.com \\
  -e PASSWORD=topsecret \\
  -v ./persist:/persist \\
  --name grist --rm \\
  -it gristlabs/grist-omnibus

Going to https://localhost:9999 I always get a 404 error

**Comment by paulfitz** [comment]
Thanks for reporting this. I tried running the same command and it worked out for me. Any obvious errors on the console?

Oh oh oh hang on, for that command you'll have a `http` server, not a `https` server. Try visiting http://localhost:9999 instead of https://localhost:9999

**Comment by metrolan** [comment]
> Oh oh oh hang on, for that command you'll have a `http` server, not a `https` server. Try visiting http://localhost:9999 instead of https://localhost:9999

Well, I was pretty sure I've had tried http, but it seems I wan numb last night. 

Many thans!!

**Comment by Spoffy** [comment]
Hey @metrolan  - Going to close this issue as it looks like it's resolved. Feel free to reopen it if it isn't :slightly_smiling_face:
