### ISSUE TITLE
Docker image is broken

### ISSUE THREAD

**Issue by al-indigo** [gristlabs/grist-omnibus#27]
I suppose something is broken in docker variant of launch. I've tried a bunch of variants with several machines (Windows 11+Docker WSL2, Almalinux 9.4 + Docker) with resolvable domains:

```
docker run -p 9999:80 -e URL=http://altair.local:9999 -e TEAM=test -e EMAIL=al@masked.domain -e PASSWORD=qwerty -v /home/al/tmp/grist-test:/persist --name grist --rm -it gristlabs/grist-omnibus

docker run -p 9999:80 -e URL=http://altair:9999 -e TEAM=test -e EMAIL=al@masked.domain -e PASSWORD=qwerty -v /home/al/tmp/grist-test:/persist --name grist --rm -it gristlabs/grist-omnibus

docker run -p 9999:80 -e URL=http://localhost:9999 -e TEAM=test -e EMAIL=al@masked.domain -e PASSWORD=qwerty -v /home/al/tmp/grist-test:/persist --name grist --rm -it gristlabs/grist-omnibus

docker run -p 9999:80 -e URL=http://192.168.122.1:9999 -e TEAM=test -e EMAIL=al@masked.domain -e PASSWORD=qwerty -v /home/al/tmp/grist-test:/persist --name grist --rm -it gristlabs/grist-omnibus

docker run -p 9999:80 -e URL=http://127.0.0.1:9999 -e TEAM=test -e EMAIL=al
@masked.domain -e PASSWORD=qwerty -v /home/al/tmp/grist-test:/persist --name grist --rm -it gristlabs/grist-om
nibus

docker run -p 9999:80 -e URL=http://grist.intra.ORGNAME.REALDOMAIN:9999 -e TEAM=test -e EMAIL=al
@masked.domain -e PASSWORD=qwerty -v /home/al/tmp/grist-test:/persist --name grist --rm -it gristlabs/grist-om
nibus

```
and the same with https-version. All of these fails on both machine the same way:

> Welcome to Grist.
> In quiet mode, see http://localhost:17100 to use.
> For full logs, re-run with DEBUG=1
> Setting up database...
> ApiError: Domain is not permitted: Invalid domain value.
>     at HomeDBManager.unwrapQueryResult (/grist/_build/app/gen-server/lib/homedb/HomeDBManager.js:2255:15)
>     at setupDb (/grist/_build/stubs/app/server/server.js:98:16)
>     at async main (/grist/_build/stubs/app/server/server.js:134:9) {
>   status: 400,
>   details: undefined
> }
> error [grist-omnibus] grist failed: exited with 0

All the hosts I mentioned above are resolvable on the hosts, I've double-checked.

How can I fix it? (-e DEBUG=1 doesn't add any useful info)

**Comment by paulfitz** [comment]
Ah, that reads like `TEAM=test` is not a permitted value. Try something else, like `TEAM=something`. Sorry for this, it is an accidental limit inherited from our SaaS, where team names end up being subdomains and we forbid some that might be confusing.
https://github.com/gristlabs/grist-core/blob/d6701debb114fc832a53efa090c634ef8001f052/app/common/orgNameUtils.ts#L9

**Comment by al-indigo** [comment]
Thanks, that fixed the issue
