### ISSUE TITLE
Bad Request Unregistered redirect_uri when trying login

### ISSUE THREAD

**Issue by ianzhuo** [gristlabs/grist-omnibus#6]
Hi @paulfitz ,
I run girst-omnibus using example setting as below, but when trying to login with email I got error message "Bad Request Unregistered redirect_uri".

How can I solve this problem?

```
mkdir -p /tmp/grist-test
sudo docker run \
  -p 80:80 -p 443:443 \
  -e URL=https://grist.mydomain.tld \
  -e HTTPS=auto \
  -e TEAM=cool-beans \
  -e EMAIL=owner@example.com \
  -e PASSWORD=topsecret \
  -v /tmp/grist-test:/persist \
  --name grist --rm \
  -it gristlabs/grist-omnibus  # or grist-ee-omnibus for enterprise
```

![image](https://github.com/gristlabs/grist-omnibus/assets/1394735/ad73c275-0304-423e-b612-630f52e0b952)

**Comment by dsagal** [comment]
I'd guess it is important that the `URL` variable is set correctly. Your example shows `-e URL=https://grist.example.com`, which does not seem right.

**Comment by ianzhuo** [comment]
> I'd guess it is important that the `URL` variable is set correctly. Your example shows `-e URL=https://grist.example.com`, which does not seem right.

Hi, I've properly set URL using "https://grist.mydomain.tld", but there still have the problem on redirect_uri because redirect_uri using "http://grist.mydomain.tld" instead of "https://girst.mydomain.tld".
Any clue how to modify `redirect_uri` value from "http" to https"?

**Comment by dsagal** [comment]
I was just able to run this example successfully without running into trouble like you describe. Can you check if you are using the latest docker image? `docker pull gristlabs/grist-omnibus:latest` should update it.

**Comment by ianzhuo** [comment]
@dsagal, 
I checked my docker image list, and there are two grist-omnibus images exist!!
After I deleted them all and re-run script again, then everything is back to normal.
thanks for you kindly support.

![image](https://github.com/gristlabs/grist-omnibus/assets/1394735/1df0614a-a0ea-475b-b65c-e5d626a9507d)
